Repository LengTech11/VisionCareAI-Detect-Consult, pull requests merged in 2024-06, with the labels that each got.

#38 37-fix-register-screen
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/pubspec.lock
Labels: bug, S, flutter

#40 close #15 create on board screen
  disease_detector_app/assets/images/onboarding/onboarding1.gif
  disease_detector_app/assets/images/onboarding/onboarding2.gif
  disease_detector_app/assets/images/onboarding/onboarding3.gif
  disease_detector_app/assets/images/onboarding/onboarding4.gif
  disease_detector_app/ios/Podfile.lock
  disease_detector_app/ios/Runner.xcodeproj/project.pbxproj
  disease_detector_app/ios/Runner.xcworkspace/contents.xcworkspacedata
  disease_detector_app/lib/config/themes/color.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/onboarding/onboarding_info.dart
  disease_detector_app/lib/screens/onboarding/onboarding_items.dart
  disease_detector_app/lib/screens/onboarding/onboarding_view.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
Labels: S, flutter

#44 42 fix outline button
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/widgets/outlined_button.dart
Labels: enhancement, XS, flutter

#51 WIP #46-profile-screen
  disease_detector_app/.metadata
  disease_detector_app/assets/icons/empty_pf.svg
  disease_detector_app/lib/config/themes/color.dart
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/firebase_helpers/firebase_firestore_helper/firebase_firestore_helper.dart
  disease_detector_app/lib/firebase_helpers/firebase_storage_helper/firebase_storage_helper.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/model/user_model/user_model.dart
  disease_detector_app/lib/provider/provider.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/change_password_screen.dart
  disease_detector_app/lib/screens/account_page/ok.dart
  disease_detector_app/lib/screens/account_page/widget/change_password.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/utils/helper/helper_function.dart
  disease_detector_app/lib/widgets/menuItem.dart
  disease_detector_app/lib/widgets/tile_button.dart
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
  disease_detector_app/windows/flutter/generated_plugin_registrant.cc
  disease_detector_app/windows/flutter/generated_plugins.cmake
Labels: enhancement

#53 WIP #52-remove-safe-area
  disease_detector_app/lib/screens/home/home_screen.dart
Labels: enhancement

#57 close #56-fix-log-out-function
  disease_detector_app/lib/provider/provider.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/home/home_screen.dart
Labels: bug, enhancement

#59 WIP #58-fix-view-profile-picture
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
Labels: bug

#60 close uploading screen
  disease_detector_app/lib/screens/diseases/disease_screen.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
Labels: wontfix

#62 WIP #58-fix-view-profile-picture
  disease_detector_app/assets/images/blank-profile-picture-973460_1280.webp
  disease_detector_app/lib/firebase_helpers/firebase_storage_helper/firebase_storage_helper.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
Labels: enhancement

#64 WIP #63-fix-login-screen
  disease_detector_app/assets/icons/google.svg
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/widgets/outlined_button.dart
Labels: enhancement

#69 close #68 auth api
  eyes_disease_backend/laravel-app/app/Http/Controllers/Api/ApiController.php
  eyes_disease_backend/laravel-app/app/Models/User.php
  eyes_disease_backend/laravel-app/bootstrap/app.php
  eyes_disease_backend/laravel-app/composer.json
  eyes_disease_backend/laravel-app/composer.lock
  eyes_disease_backend/laravel-app/config/sanctum.php
  eyes_disease_backend/laravel-app/database/migrations/0001_01_01_000000_create_users_table.php
  eyes_disease_backend/laravel-app/database/migrations/2024_06_11_165807_create_personal_access_tokens_table.php
  eyes_disease_backend/laravel-app/routes/api.php
Labels: API

#79 Close #78-create-show-error-message-dialog
  disease_detector_app/lib/config/constants.dart
Labels: XS, flutter

#81 Close #80-call-login-api-service-on-login-screen
  disease_detector_app/lib/api_service/api/login_api.dart
  disease_detector_app/lib/api_service/api/sample_apit.dart
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: XS, flutter

#83 Close #82-create-register-api-service-to-request-register-from-server
  disease_detector_app/lib/api_service/api/register_api.dart
  disease_detector_app/lib/model/register_model/register_response_model.dart
Labels: XS, flutter

#85 Close #84-call-register-api-on-register-screen
  disease_detector_app/lib/api_service/api/register_api.dart
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/screens/register/register_screen.dart
Labels: XS, flutter

#87 Close #86-add-phoneNumber-age-and-gender-text-field-on-register-screen
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/widgets/drop_down_menu.dart
Labels: S, XS, flutter

#89 Close #88-remove-old-profile-provider-from-account-screen
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
Labels: XS, flutter

#91 Close #90 create getProfile api service to request server the user pr…
  disease_detector_app/lib/api_service/api/user_profile_api.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/model/user_profile_model/user_profile_model.dart
  disease_detector_app/lib/provider/user_profile_provider.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  eyes_disease_backend/laravel-app/app/Http/Controllers/Api/ApiController.php
Labels: XS, flutter

#93 Close #92-create-log-out-provider-and-call-it-on-profile-screen
  disease_detector_app/lib/provider/user_profile_provider.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
Labels: XS, flutter

#95 Close #94 fix login screen route to home screen
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: enhancement, XS

#97 Close #96 fix register screen route to home screen
  disease_detector_app/lib/screens/register/register_screen.dart
Labels: enhancement, XS

#99 Close #98 fix MyTextFormField when onTapOutside, keyboard is hiden
  disease_detector_app/lib/provider/user_profile_provider.dart
  disease_detector_app/lib/widgets/my_text_form_field.dart
Labels: enhancement, XS

#100 WIP #67 enhance onboarding screen
  disease_detector_app/devtools_options.yaml
  disease_detector_app/lib/screens/onboarding/onboarding_view.dart
Labels: enhancement, XS
