Repository LengTech11/VisionCareAI-Detect-Consult, pull requests merged in 2024-07, with the labels that each got.

#109 Close #108 edit image upload screen and profile user picture
  disease_detector_app/assets/images/blank-profile-picture-973460_1280.webp
  disease_detector_app/assets/images/blank_profile.jpg
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
Labels: enhancement, XS

#111 WIP #110 view pdf document and fetch disease api
  disease_detector_app/lib/api_service/client/dio_http_client.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
  disease_detector_app/web/index.html
  disease_detector_app/windows/flutter/generated_plugin_registrant.cc
  disease_detector_app/windows/flutter/generated_plugins.cmake
Labels: S, flutter

#115 Close #114 create list view of disease and show bottom sheet of disease
  disease_detector_app/lib/config/app_config/app_config.dart
  disease_detector_app/lib/provider/disease_provider.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/lib/widgets/eca_listtile.dart
  disease_detector_app/lib/widgets/eca_show_btm_sheet.dart
  disease_detector_app/linux/flutter/generated_plugin_registrant.cc
  disease_detector_app/linux/flutter/generated_plugins.cmake
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/windows/flutter/generated_plugin_registrant.cc
  disease_detector_app/windows/flutter/generated_plugins.cmake
Labels: S, flutter

#121 Close #120 check null on list of disease to prevent null safety
  disease_detector_app/lib/screens/home/image_upload_screen.dart
Labels: enhancement, XS

#119 WIP #118 create screen to view pdf of document
  disease_detector_app/assets/icons/PDF_file_icon.svg
  disease_detector_app/lib/model/disease_model.dart
  disease_detector_app/lib/provider/disease_provider.dart
  disease_detector_app/lib/provider/document_provider.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/pdf_screen/pdf_screen.dart
  disease_detector_app/lib/screens/view_pdf_screen/view_pdf_screen.dart
  disease_detector_app/lib/widgets/eca_show_btm_sheet.dart
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
Labels: S, flutter

#117 Your commit message
  eyes_disease_backend/laravel-app/app/Http/Controllers/Api/ApiController.php
  eyes_disease_backend/laravel-app/app/Http/Controllers/DocumentController.php
  eyes_disease_backend/laravel-app/routes/api.php
Labels: API

#131 Close #125 reset password
  disease_detector_app/lib/api_service/api/change_password_api.dart
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/model/change_password/change_password_response_model.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/change_password.dart
  disease_detector_app/lib/screens/account_page/change_password_screen.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
Labels: S, flutter

#133 Close #132 create show message dialog
  disease_detector_app/lib/config/app_config/app_config.dart
  disease_detector_app/lib/config/constants.dart
Labels: enhancement, S

#135 close #134 fix docs api
  eyes_disease_backend/laravel-app/app/Http/Controllers/Api/ApiController.php
Labels: API

#137 Close #136 save token to storage and check isFirstInstall app
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/onboarding/onboarding_view.dart
  disease_detector_app/lib/storage/check_first_install.dart
  disease_detector_app/lib/storage/token_storage.dart
Labels: enhancement, S

#141 Close #140 fix docs
  disease_detector_app/lib/api_service/api/document_api.dart
  disease_detector_app/lib/provider/document_provider.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/lib/widgets/eca_show_btm_sheet.dart
Labels: enhancement, S

#144 close #143 enhance history UI
  disease_detector_app/lib/screens/diseases/disease_screen.dart
  disease_detector_app/lib/screens/diseases/widget/DiseaseCategories.dart
  disease_detector_app/lib/widgets/historyList.dart
  disease_detector_app/lib/widgets/plantList.dart
  disease_detector_app/lib/widgets/widgets.dart
Labels: enhancement, S

#149 Close #148 Switch Language
  disease_detector_app/l10n.yaml
  disease_detector_app/lib/config/app_config/app_config.dart
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/l10n/l10n.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/change_password.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/screens/diseases/disease_screen.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/widgets/bottomNavigation.dart
  disease_detector_app/linux/flutter/generated_plugin_registrant.cc
  disease_detector_app/linux/flutter/generated_plugins.cmake
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
  disease_detector_app/windows/flutter/generated_plugin_registrant.cc
  disease_detector_app/windows/flutter/generated_plugins.cmake
Labels: enhancement, S
