Repository LengTech11/VisionCareAI-Detect-Consult, pull requests merged in 2024-05, with the labels that each got.

#3 close #2 install dependencies flutter
  disease_detector_app/assets/fonts/Poppins-Bold.ttf
  disease_detector_app/assets/fonts/Poppins-Regular.ttf
  disease_detector_app/assets/images/background.jpg
  disease_detector_app/assets/images/image_1.jpg
  disease_detector_app/assets/images/image_2.jpg
  disease_detector_app/assets/images/me.jpg
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
Labels: XS, flutter, setup

#9 close #8 setup dark and light mode constants
  disease_detector_app/lib/config/constants.dart
Labels: S, flutter

#10 close #7 create reuseable widget and homePage,accountPage
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/pages/accountPage.dart
  disease_detector_app/lib/pages/homePage.dart
  disease_detector_app/lib/pages/plantPage.dart
  disease_detector_app/lib/widgets/bottomNavigation.dart
  disease_detector_app/lib/widgets/buttons.dart
  disease_detector_app/lib/widgets/checkMark.dart
  disease_detector_app/lib/widgets/customTabBar.dart
  disease_detector_app/lib/widgets/dialog.dart
  disease_detector_app/lib/widgets/divider.dart
  disease_detector_app/lib/widgets/dropDownBox.dart
  disease_detector_app/lib/widgets/glass.dart
  disease_detector_app/lib/widgets/menuItem.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
  disease_detector_app/lib/widgets/moreMenu.dart
  disease_detector_app/lib/widgets/plantList.dart
  disease_detector_app/lib/widgets/searchBar.dart
  disease_detector_app/lib/widgets/sortMenu.dart
  disease_detector_app/lib/widgets/textfield.dart
  disease_detector_app/lib/widgets/themeToggleSwitch.dart
  disease_detector_app/lib/widgets/widgets.dart
Labels: M, flutter

#12 ui_update
  disease_detector_app/android/app/build.gradle
  disease_detector_app/android/build.gradle
  disease_detector_app/assets/images/logo.png
  disease_detector_app/assets/logo/logo.png
  disease_detector_app/assets/logo/long_logo.png
  disease_detector_app/assets/logo/splash.png
  disease_detector_app/lib/config/themes/app_size.dart
  disease_detector_app/lib/config/themes/color.dart
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/plant/plant_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/screens/splash_screen/splash_screen.dart
  disease_detector_app/lib/utils/custom_text_theme/custom_text_theme.dart
  disease_detector_app/lib/utils/device/device_utility.dart
  disease_detector_app/lib/utils/helper/helper_function.dart
  disease_detector_app/lib/widgets/bottomNavigation.dart
  disease_detector_app/lib/widgets/customTabBar.dart
  disease_detector_app/lib/widgets/elevated_button_theme.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
  disease_detector_app/lib/widgets/my_button.dart
  disease_detector_app/lib/widgets/my_text_form_field.dart
  disease_detector_app/lib/widgets/searchBar.dart
  disease_detector_app/lib/widgets/sortMenu.dart
  disease_detector_app/linux/flutter/generated_plugin_registrant.cc
  disease_detector_app/linux/flutter/generated_plugins.cmake
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
  disease_detector_app/test/widget_test.dart
  disease_detector_app/windows/flutter/generated_plugin_registrant.cc
  disease_detector_app/windows/flutter/generated_plugins.cmake
Labels: S, flutter

#19 13-fix_search_bar_on_login_screen
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: enhancement

#25 add flutter screen util
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/config/themes/app_size.dart
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/plant/plant_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/utils/custom_text_theme/custom_text_theme.dart
  disease_detector_app/lib/widgets/bottomNavigation.dart
  disease_detector_app/lib/widgets/buttons.dart
  disease_detector_app/lib/widgets/checkMark.dart
  disease_detector_app/lib/widgets/customTabBar.dart
  disease_detector_app/lib/widgets/dialog.dart
  disease_detector_app/lib/widgets/divider.dart
  disease_detector_app/lib/widgets/dropDownBox.dart
  disease_detector_app/lib/widgets/elevated_button_theme.dart
  disease_detector_app/lib/widgets/glass.dart
  disease_detector_app/lib/widgets/menuItem.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
  disease_detector_app/lib/widgets/moreMenu.dart
  disease_detector_app/lib/widgets/my_button.dart
  disease_detector_app/lib/widgets/my_text_form_field.dart
  disease_detector_app/lib/widgets/plantList.dart
  disease_detector_app/lib/widgets/searchBar.dart
  disease_detector_app/lib/widgets/sortMenu.dart
  disease_detector_app/lib/widgets/textfield.dart
  disease_detector_app/lib/widgets/themeToggleSwitch.dart
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
Labels: XS, flutter

#29 close #27 setup docker to laravel backend
  eyes_disease_backend/Dockerfile
  eyes_disease_backend/Makefile
  eyes_disease_backend/docker-compose.yml
  eyes_disease_backend/laravel-app/.editorconfig
  eyes_disease_backend/laravel-app/.env.example
  eyes_disease_backend/laravel-app/.gitattributes
  eyes_disease_backend/laravel-app/.gitignore
  eyes_disease_backend/laravel-app/README.md
  eyes_disease_backend/laravel-app/app/Http/Controllers/Controller.php
  eyes_disease_backend/laravel-app/app/Models/User.php
  eyes_disease_backend/laravel-app/app/Providers/AppServiceProvider.php
  eyes_disease_backend/laravel-app/artisan
  eyes_disease_backend/laravel-app/bootstrap/app.php
  eyes_disease_backend/laravel-app/bootstrap/cache/.gitignore
  eyes_disease_backend/laravel-app/bootstrap/providers.php
  eyes_disease_backend/laravel-app/composer.json
  eyes_disease_backend/laravel-app/composer.lock
  eyes_disease_backend/laravel-app/config/app.php
  eyes_disease_backend/laravel-app/config/auth.php
  eyes_disease_backend/laravel-app/config/cache.php
  eyes_disease_backend/laravel-app/config/database.php
  eyes_disease_backend/laravel-app/config/filesystems.php
  eyes_disease_backend/laravel-app/config/logging.php
  eyes_disease_backend/laravel-app/config/mail.php
  eyes_disease_backend/laravel-app/config/queue.php
  eyes_disease_backend/laravel-app/config/services.php
  eyes_disease_backend/laravel-app/config/session.php
  eyes_disease_backend/laravel-app/database/.gitignore
  eyes_disease_backend/laravel-app/database/factories/UserFactory.php
  eyes_disease_backend/laravel-app/database/migrations/0001_01_01_000000_create_users_table.php
  eyes_disease_backend/laravel-app/database/migrations/0001_01_01_000001_create_cache_table.php
  eyes_disease_backend/laravel-app/database/migrations/0001_01_01_000002_create_jobs_table.php
  eyes_disease_backend/laravel-app/database/seeders/DatabaseSeeder.php
  eyes_disease_backend/laravel-app/package.json
  eyes_disease_backend/laravel-app/phpunit.xml
  eyes_disease_backend/laravel-app/public/.htaccess
  eyes_disease_backend/laravel-app/public/favicon.ico
  eyes_disease_backend/laravel-app/public/index.php
  eyes_disease_backend/laravel-app/public/robots.txt
  eyes_disease_backend/laravel-app/resources/css/app.css
  eyes_disease_backend/laravel-app/resources/js/app.js
  eyes_disease_backend/laravel-app/resources/js/bootstrap.js
  eyes_disease_backend/laravel-app/resources/views/welcome.blade.php
  eyes_disease_backend/laravel-app/routes/console.php
  eyes_disease_backend/laravel-app/routes/web.php
  eyes_disease_backend/laravel-app/storage/app/.gitignore
  eyes_disease_backend/laravel-app/storage/app/public/.gitignore
  eyes_disease_backend/laravel-app/storage/framework/.gitignore
  eyes_disease_backend/laravel-app/storage/framework/cache/.gitignore
  eyes_disease_backend/laravel-app/storage/framework/cache/data/.gitignore
  eyes_disease_backend/laravel-app/storage/framework/sessions/.gitignore
  eyes_disease_backend/laravel-app/storage/framework/testing/.gitignore
  eyes_disease_backend/laravel-app/storage/framework/views/.gitignore
  eyes_disease_backend/laravel-app/storage/logs/.gitignore
  eyes_disease_backend/laravel-app/tests/Feature/ExampleTest.php
  eyes_disease_backend/laravel-app/tests/TestCase.php
  eyes_disease_backend/laravel-app/tests/Unit/ExampleTest.php
  eyes_disease_backend/laravel-app/vite.config.js
Labels: config

#28 fix validation, hint, style, filled color, error text on text field
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/utils/custom_text_theme/custom_text_theme.dart
  disease_detector_app/lib/widgets/moreMenu.dart
  disease_detector_app/lib/widgets/my_button.dart
  disease_detector_app/lib/widgets/my_text_form_field.dart
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
Labels: bug, M, flutter

#31 Review 30-config-firebase-and-signin-using-email-and-gmail
  disease_detector_app/android/app/build.gradle
  disease_detector_app/android/app/google-services.json
  disease_detector_app/android/settings.gradle
  disease_detector_app/firebase.json
  disease_detector_app/lib/firebase_helpers/firebase_auth/firebase_auth_helpers.dart
  disease_detector_app/lib/firebase_options.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/model/user_model/user_model.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/macos/Flutter/GeneratedPluginRegistrant.swift
  disease_detector_app/pubspec.lock
  disease_detector_app/pubspec.yaml
  disease_detector_app/windows/flutter/generated_plugin_registrant.cc
  disease_detector_app/windows/flutter/generated_plugins.cmake
Labels: S, flutter, config

#33 Review 32-sign-out-email-and-gmail
  disease_detector_app/lib/firebase_helpers/firebase_auth/firebase_auth_helpers.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: S, flutter
