Repository LengTech11/VisionCareAI-Detect-Consult, pull requests merged in 2024-08, with the labels that each got.

#151 WIP #150 enhance login screen
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: enhancement, S

#155 WIP #154 resolve null safty on list of diseasetile
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/screens/home/image_upload_screen.dart
Labels: enhancement, S

#157 Close #156 enhance profile image
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
Labels: enhancement, XS

#159 Close #158 add app bar
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/diseases/disease_screen.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
Labels: enhancement, XS

#161 Close #160 fix log out feature
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
Labels: enhancement, XS

#163 Close #160 fix logout button
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/widgets/outlined_button.dart
  disease_detector_app/lib/widgets/widgets.dart
Labels: enhancement, XS

#165 Close #164 enhance check language in switchLanguageDialog()
  disease_detector_app/lib/screens/account_page/account_screen.dart
Labels: enhancement, XS

#166 Close #158 add app bar
  disease_detector_app/lib/screens/home/home_screen.dart
Labels: enhancement, XS

#168 enhance dialog loading view
  disease_detector_app/lib/config/constants.dart
Labels: enhancement, XS

#172 1710 fix history on guest
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/provider/get_history_provider.dart
  disease_detector_app/lib/screens/diseases/disease_screen.dart
  disease_detector_app/lib/widgets/historyList.dart
  disease_detector_app/pubspec.lock
Labels: enhancement, XS

#174 Close #173 fix app localization on change password screen
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/change_password_screen.dart
  disease_detector_app/pubspec.yaml
Labels: enhancement, XS

#185 184 enhance change password button
  disease_detector_app/lib/config/app_config/app_config.dart
  disease_detector_app/lib/config/constants.dart
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/pdf_screen/pdf_screen.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
Labels: enhancement, XS

#180 Close #179 enhance pdf page
  disease_detector_app/lib/screens/pdf_screen/pdf_screen.dart
Labels: enhancement, XS

#187 Close #186 enhance register screen
  disease_detector_app/lib/screens/register/register_screen.dart
Labels: enhancement, XS

#191 Close #190 remove padding from profile info
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
Labels: enhancement, XS

#205 WIP #204 fix edit profile
  disease_detector_app/lib/api_service/api/user_profile_api.dart
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/model/user_profile_model/user_profile_model.dart
  disease_detector_app/lib/provider/user_profile_provider.dart
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/edit_profile_screen.dart
  disease_detector_app/lib/screens/account_page/widget/edit_photo_bottom_sheet.dart
  disease_detector_app/lib/screens/account_page/widget/edit_profile_button.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/widgets/historyList.dart
Labels: enhancement, S

#207 WIP #205 fix login feature
  disease_detector_app/lib/api_service/api/user_profile_api.dart
  disease_detector_app/lib/config/app_config/app_config.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: enhancement, S

#211 Close #210 enhance login screen
  disease_detector_app/lib/screens/account_page/edit_profile_screen.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/screens/login/login_screen.dart
Labels: enhancement, S

#213 Close #212 add more app color
  disease_detector_app/lib/config/themes/color.dart
Labels: enhancement, XS

#215 close Implement Swagger API Docs
  eyes_disease_backend/laravel-app/app/Http/Controllers/Api/ApiController.php
  eyes_disease_backend/laravel-app/composer.json
  eyes_disease_backend/laravel-app/composer.lock
  eyes_disease_backend/laravel-app/config/l5-swagger.php
  eyes_disease_backend/laravel-app/public/swagger.json
  eyes_disease_backend/laravel-app/resources/views/vendor/l5-swagger/.gitkeep
  eyes_disease_backend/laravel-app/resources/views/vendor/l5-swagger/index.blade.php
  eyes_disease_backend/laravel-app/storage/api-docs/api-docs.json
Labels: API

#217 Close #216 add material 3 theme
  disease_detector_app/lib/config/themes/m3_theme.dart
  disease_detector_app/lib/config/themes/theme.dart
Labels: enhancement, S

#220 Close #219 add some new custom widgets which use material 3 theme
  disease_detector_app/lib/widgets/vc_dialog.dart
  disease_detector_app/lib/widgets/vc_filled_button.dart
  disease_detector_app/lib/widgets/vc_filled_icon_button.dart
  disease_detector_app/lib/widgets/vc_outlined_button.dart
  disease_detector_app/lib/widgets/vc_snack_bar.dart
  disease_detector_app/lib/widgets/vc_standart_icon_button.dart
  disease_detector_app/lib/widgets/vc_text_button.dart
  disease_detector_app/lib/widgets/vc_text_field.dart
  disease_detector_app/lib/widgets/widgets.dart
Labels: enhancement

#221 Close #218 change color of bottom navigation bar
  disease_detector_app/lib/widgets/bottomNavigation.dart
Labels: enhancement, XS

#223 Close #222 update new theme
  disease_detector_app/lib/config/themes/theme.dart
Labels: enhancement

#225 Close #224 remove old text field and replace it by new text field
  disease_detector_app/lib/config/themes/theme.dart
  disease_detector_app/lib/screens/account_page/change_password_screen.dart
  disease_detector_app/lib/screens/account_page/edit_profile_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/widgets/my_text_form_field.dart
Labels: enhancement

#227 Close #226 plex tha update ey klas bat hx
  disease_detector_app/lib/screens/account_page/account_screen.dart
  disease_detector_app/lib/screens/account_page/edit_profile_screen.dart
  disease_detector_app/lib/screens/account_page/widget/edit_profile_button.dart
  disease_detector_app/lib/screens/account_page/widget/logout_button.dart
  disease_detector_app/lib/screens/account_page/widget/profile_menu_item.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/lib/widgets/menuItemCategory.dart
  disease_detector_app/lib/widgets/themeToggleSwitch.dart
  disease_detector_app/lib/widgets/vc_dialog.dart
  disease_detector_app/lib/widgets/vc_outlined_button.dart
Labels: enhancement

#237 WIP #234 create home screen
  disease_detector_app/lib/config/app_config/app_config.dart
  disease_detector_app/lib/config/themes/m3_theme.dart
  disease_detector_app/lib/l10n/app_en.arb
  disease_detector_app/lib/l10n/app_km.arb
  disease_detector_app/lib/main.dart
  disease_detector_app/lib/provider/disease_provider.dart
  disease_detector_app/lib/screens/account_page/edit_profile_screen.dart
  disease_detector_app/lib/screens/bottom_navigation_bar/bottom_navigation_bar_screen.dart
  disease_detector_app/lib/screens/doctor/doctor_screen.dart
  disease_detector_app/lib/screens/home/home_screen.dart
  disease_detector_app/lib/screens/home/image_upload_screen.dart
  disease_detector_app/lib/screens/login/login_screen.dart
  disease_detector_app/lib/screens/register/register_screen.dart
  disease_detector_app/lib/widgets/appbar.dart
  disease_detector_app/lib/widgets/vc_clinic_card.dart
  disease_detector_app/lib/widgets/vc_doctor_card.dart
  disease_detector_app/lib/widgets/vc_list_tile.dart
  disease_detector_app/lib/widgets/widgets.dart
  disease_detector_app/pubspec.lock
Labels: M, flutter
